### ISSUE TITLE
Error with run_humann_nonhost Rule

### ISSUE THREAD

**Issue by jboconnor13** [sterrettJD/HoMi#87]
When running the HoMi pipeline with the default latest setting for the metaphlan database index, meaning the parameter for the rule `metaphlan_index=get_metaphlan_index_name(config)` is `"latest"`, I received the following error with the run_humann_nonhost rule:

rule run_humann_nonhost:
    input: data/metaphlan_db, data/humann_dbs/chocophlan, data/humann_dbs/uniref, Zim4.f5.0.r10.0.nonhost.concat/7_ZIM143.fq.gz
    output: Zim4.f5.0.r10.0.nonhost.humann/7_ZIM143/7_ZIM143_pathabundance.tsv, Zim4.f5.0.r10.0.nonhost.humann/7_ZIM143/7_ZIM143_pathcoverage.tsv, Zim4.f5.0.r10.0.nonhost.humann/7_ZIM143/7_ZIM143_genefamilies.tsv, Zim4.f5.0.r10.0.nonhost.humann/7_ZIM143/7_ZIM143_humann_temp/7_ZIM143_metaphlan_bugs_list.tsv
    jobid: 0
    reason: Forced execution
    wildcards: sample=7_ZIM143
    threads: 32
    resources: mem_mb=64000, mem_mib=61036, disk_mb=5830, disk_mib=5560, tmpdir=/scratch/alpine/joconnor@xsede.org, partition=amilan, runtime=1434, slurm=

    mkdir -p Zim4.f5.0.r10.0.nonhost.humann

    if [ "latest" = "latest" ]; then
      # read index name form the latest file
      metaphlan_db_name="$(<data/metaphlan_db//latest)"
      
      humann -i Zim4.f5.0.r10.0.nonhost.concat/7_ZIM143.fq.gz -o Zim4.f5.0.r10.0.nonhost.humann/7_ZIM143       --threads 32 --search-mode uniref90       --metaphlan-options "--bowtie2db data/metaphlan_db/"       

    else
      humann -i Zim4.f5.0.r10.0.nonhost.concat/7_ZIM143.fq.gz -o Zim4.f5.0.r10.0.nonhost.humann/7_ZIM143       --threads 32 --search-mode uniref90       --metaphlan-options "--bowtie2db data/metaphlan_db/ --index latest"       

    fi
    
Activating conda environment: ../../../../../projects/.xsede.org/joconnor/.snakemake/conda/9421bbfdb9a1863fa8a7cbc3b664de75_
/usr/bin/bash: line 5: data/metaphlan_db//latest: No such file or directory

**Comment by jboconnor13** [comment]
When this is resolved with manual installation https://github.com/sterrettJD/HoMi/issues/86 and specifying the index in the config by adding `metaphlan_index_name: mpa_vOct22_CHOCOPhlAnSGB_202212`, I run into the following error. This is because there is no mpa_pkl file.

rule run_humann_nonhost:
    input: data/metaphlan_db, data/humann_dbs/chocophlan, data/humann_dbs/uniref, Zim4.f5.0.r10.0.nonhost.concat/12_ZIM159.fq.gz
    output: Zim4.f5.0.r10.0.nonhost.humann/12_ZIM159/12_ZIM159_pathabundance.tsv, Zim4.f5.0.r10.0.nonhost.humann/12_ZIM159/12_ZIM159_pathcoverage.tsv, Zim4.f5.0.r10.0.nonhost.humann/12_ZIM159/12_ZIM159_genefamilies.tsv, Zim4.f5.0.r10.0.nonhost.humann/12_ZIM159/12_ZIM159_humann_temp/12_ZIM159_metaphlan_bugs_list.tsv
    jobid: 0
    reason: Forced execution
    wildcards: sample=12_ZIM159
    threads: 32
    resources: mem_mb=64000, mem_mib=61036, disk_mb=6983, disk_mib=6660, tmpdir=/scratch/alpine/joconnor@xsede.org, partition=amilan, runtime=1434, slurm=


    mkdir -p Zim4.f5.0.r10.0.nonhost.humann

    if [ "mpa_vOct22_CHOCOPhlAnSGB_202212" = "latest" ]; then
      # read index name form the latest file
      metaphlan_db_name="$(<data/metaphlan_db//mpa_vOct22_CHOCOPhlAnSGB_202212)"
      
      humann -i Zim4.f5.0.r10.0.nonhost.concat/12_ZIM159.fq.gz -o Zim4.f5.0.r10.0.nonhost.humann/12_ZIM159       --threads 32 --search-mode uniref90       --metaphlan-options "--bowtie2db data/metaphlan_db/"       

    else
      humann -i Zim4.f5.0.r10.0.nonhost.concat/12_ZIM159.fq.gz -o Zim4.f5.0.r10.0.nonhost.humann/12_ZIM159       --threads 32 --search-mode uniref90       --metaphlan-options "--bowtie2db data/metaphlan_db/ --index mpa_vOct22_CHOCOPhlAnSGB_202212"       

    fi
    
Activating conda environment: ../../../../../projects/.xsede.org/joconnor/.snakemake/conda/9421bbfdb9a1863fa8a7cbc3b664de75_
CRITICAL ERROR: Error executing: /projects/.xsede.org/joconnor/.snakemake/conda/9421bbfdb9a1863fa8a7cbc3b664de75_/bin/metaphlan /gpfs/alpine1/scratch/joconnor@xsede.org/HoMi/Zim4.f5.0.r10.0.nonhost.humann/12_ZIM159/12_ZIM159_humann_temp/tmp0kf_hp61/tmppkme36_s --bowtie2db data/metaphlan_db/ --index mpa_vOct22_CHOCOPhlAnSGB_202212 -o /gpfs/alpine1/scratch/joconnor@xsede.org/HoMi/Zim4.f5.0.r10.0.nonhost.humann/12_ZIM159/12_ZIM159_humann_temp/12_ZIM159_metaphlan_bugs_list.tsv --input_type fastq --bowtie2out /gpfs/alpine1/scratch/joconnor@xsede.org/HoMi/Zim4.f5.0.r10.0.nonhost.humann/12_ZIM159/12_ZIM159_humann_temp/12_ZIM159_metaphlan_bowtie2.txt --nproc 32

Error message returned from metaphlan :
Error: Unable to find the mpa_pkl file at: mpa_pklExiting...

**Comment by sterrettJD** [comment]
Hey Jack,

The issue is that the previous wget link was to the bowtie indexes, not the main metaphlan databases. Here is the correct version.

> wget http://cmprod1.cibio.unitn.it/biobakery4/metaphlan_databases/mpa_vOct22_CHOCOPhlAnSGB_202403.tar
> tar -xvf mpa_vOct22_CHOCOPhlAnSGB_202403.tar
> rm mpa_vOct22_CHOCOPhlAnSGB_202403.tar

I've updated this in the manual option in the rule.
